development:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Lowdown] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  # Create your own unique secret using 'SecureRandom(64)' in IRB
  secret_token: '526e98c3f4af6476a1bc4b40a48f0f87ee27ebb92b73ee0a9075aeeedabd5ed12a7ddc6d72fdebb387cc13ef7d2d62af14259b055146bb19ef78ccb81741b620'

test:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Lowdown] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  # Create your own unique secret using 'SecureRandom(64)' in IRB
  secret_token: '526e98c3f4af6476a1bc4b40a48f0f87ee27ebb92b73ee0a9075aeeedabd5ed12a7ddc6d72fdebb387cc13ef7d2d62af14259b055146bb19ef78ccb81741b620'

production:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Lowdown] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  # Create your own unique secret using 'SecureRandom(64)' in IRB
  secret_token: '526e98c3f4af6476a1bc4b40a48f0f87ee27ebb92b73ee0a9075aeeedabd5ed12a7ddc6d72fdebb387cc13ef7d2d62af14259b055146bb19ef78ccb81741b620'
