development:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Lowdown] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  mailer_host: 'dev.example.org/service'
  devise_mailer_sender: 'me@example.com'

test:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Lowdown] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  mailer_host: 'test.example.org/service'
  devise_mailer_sender: 'me@example.com'

staging:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Lowdown] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  mailer_host: 'staging.example.org/service'
  devise_mailer_sender: 'me@example.com'

production:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Lowdown] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'
  mailer_host: 'apps.example.org/service'
  devise_mailer_sender: 'me@example.com'
